apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: myapp-eks-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral